#!/usr/bin/env bash

set -eou pipefail

USER="$(whoami)"
HOST="$(hostname)"

NIX_CONFIG="experimental-features = nix-command flakes" \
	nix-shell -p home-manager \
	--run "home-manager switch --flake .#${USER}@${HOST} ${@}"
