{
  self,
  config,
  pkgs,
  lib,
  ...
}:
let
  inherit (self.lib) mkEnabledOption;
  cfg = config.x.home.development.ai.mcpServers;
in
{
  options.x.home.development.ai.mcpServers = {
    enable = mkEnabledOption "enable shared MCP server configuration for AI agents";

    servers = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      readOnly = true;
      description = "MCP servers generated by mcp-servers-nix for agent clients.";
    };
  };

  config = lib.mkIf (config.x.home.development.enable && cfg.enable) {
    x.home.development.ai.mcpServers.servers =
      (self.inputs.mcp-servers.lib.evalModule pkgs {
        programs = {
          context7.enable = true;
        };
      }).config.settings.servers;

    programs.mcp = {
      enable = true;
      servers = cfg.servers;
    };
  };
}
